// <auto-generated />
using Factors.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Factors.Web.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20240612120001_AddAppSettings")]
partial class AddAppSettings : Migration
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("SQLite:Autoincrement", true);

        modelBuilder.Entity("Factors.Web.Models.Entities.AppSetting", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<string>("Value")
                .HasMaxLength(2000)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("Key")
                .IsUnique();

            b.ToTable("AppSettings", (string)null);
        });
#pragma warning restore 612, 618
    }
}
